# Generated by Django 5.1.6 on 2025-05-07 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ipaddress', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TcpPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=50)),
                ('source_ip', models.CharField(max_length=50)),
                ('destination_ip', models.CharField(max_length=50)),
                ('protocol', models.CharField(max_length=20)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tcp_packets', to='app_1.equipment')),
            ],
        ),
    ]
